#!/bin/sh

filename="${1}"
title=$(< "${filename}" head -n1 | sed 's/<!-- Title: //; s/-->//')

cat << EOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
	<meta name="viewport" content="width=1024">
	<link rel='stylesheet' type='text/css' href="/style.css">
	<link rel="icon" type="image/x-icon" href="/favicon.ico">
	<title>${title}</title>
</head>
<body>
	<table id="bar">
	<tr>
		<td id='header-name'>Suleyman Farajli</td>
		<td id='quote'></td>
	</tr>
	</table>
	<script>
		let quotes = ["Uncensored", "Oh mamma mia!", "Memento Mori!", "Oh là là!", "C'est légal parce que je le veux", "Sweet Dreams Are Made of This"];
		let randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
		document.getElementById("quote").innerText = randomQuote;
	</script>

	<hr class="separator">

<div class="menu">
	<a class="menu_item" href="/home/index.html">Home/</a>
	<a class="menu_item" href="/posts/posts.html">Posts/</a>
	<a class="menu_item" href="/archive/archive.html">Archive/</a>
	<a class="menu_item right_menu_item" href="https://git.farajli.net">Git</a>
</div>
<div class="text">
	$(sed '1 s/<!--.*-->//' "${filename}" | smu)
</div>
<p id="copyleft"><br>copyleft (c) 2024-2025 Suleyman Farajli</p>

</body>
</html>
EOF
